version: "3.8"

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: ambitiousYou_postgres
  #   environment:
  #     POSTGRES_DB: ambitiousYouLocalDB
  #     POSTGRES_USER: hemant
  #     POSTGRES_PASSWORD: hemant_at_AmbitiousYouDB_9045
  #     POSTGRES_HOST_AUTH_METHOD: md5
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U hemant"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ambitiousYou_nextjs
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    # environment:
    #   DATABASE_URL: postgres://hemant:hemant_at_AmbitiousYouDB_9045@postgres:5432/ambitiousYouLocalDB
    depends_on:
      postgres:
        condition: service_healthy
